//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyurvedOnCall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long AppointmentId { get; set; }
        public long DoctorId { get; set; }
        public string Fullname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string GenderId { get; set; }
        public string Complaint { get; set; }
        public string Allergies { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public bool IsConfirm { get; set; }
        public bool IsRejected { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
