//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyurvedOnCall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvailableSlab
    {
        public long AvailableSlabId { get; set; }
        public long DoctorId { get; set; }
        public bool IsAllDay { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
