//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AyurvedOnCall.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplete
    {
        public long EmailTempleteId { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public string HashTag { get; set; }
        public string FromEmail { get; set; }
    }
}
